In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply
%matplotlib inline
pd.set_option('display.max_columns',None)

In [11]:
X_train = pd.read_csv('X_train_final.csv')
X_test = pd.read_csv('X_test_final.csv')
y_train = pd.read_csv('y_train_final.csv')
y_test = pd.read_csv('y_test_updated.csv')
X_train.head()

MSSubClass  MSZoning  Neighborhood  OverallQual  OverallCond  YearRemodAdd  \
0    0.000000      0.75      0.954545     0.888889         0.50      0.016393   
1    0.000000      0.75      0.363636     0.444444         0.50      0.786885   
2    0.058824      0.75      0.727273     0.444444         0.75      0.065574   
3    0.000000      0.75      0.409091     0.777778         0.50      0.114754   
4    0.000000      0.75      0.681818     0.666667         0.50      0.081967   

   RoofStyle  Exterior1st  BsmtQual  BsmtExposure  BsmtFinSF1  TotalBsmtSF  \
0        1.0          0.9      1.00          0.75    0.021239     0.568309   
1        1.0          0.3      0.50          0.25    0.000000     0.278852   
2        0.0          0.2      0.75          0.25    0.315487     0.273238   
3        1.0          0.9      0.75          0.25    0.538938     0.489083   
4        0.0          1.0      0.75          0.25    0.000000     0.480661   

   HeatingQC  CentralAir  1stFlrSF  GrLivArea  KitchenQual  Fireplaces  \
0       1.00         1.0  0.749329   0.644108     0.666667    0.333333   
1       0.75         0.0  0.434020   0.373074     0.333333    0.000000   
2       1.00         1.0  0.467252   0.401640     0.333333    0.000000   
3       1.00         1.0  0.714467   0.614140     0.666667    0.666667   
4       1.00         1.0  0.674041   0.579391     0.666667    0.333333   

   FireplaceQu  GarageType  GarageFinish  GarageCars  GarageCond  PavedDrive  \
0          0.8         0.8      0.333333        0.75         1.0         1.0   
1          0.2         0.4      0.333333        0.25         1.0         1.0   
2          0.2         0.4      0.333333        0.50         1.0         1.0   
3          0.8         0.8      0.666667        0.75         1.0         1.0   
4          0.6         0.8      0.666667        0.75         1.0         1.0   

   SaleCondition  
0           1.00  
1           0.75  
2           0.75  
3           0.75  
4           0.75

In [12]:
y_train.head()

SalePrice
0  12.659734
1  11.603680
2  12.004568
3  12.509874
4  12.230765

In [13]:
X_test.head()


MSSubClass  MSZoning  Neighborhood  OverallQual  OverallCond  YearRemodAdd  \
0    0.000000      0.75      0.727273     0.555556        0.250      0.540984   
1    0.176471      0.75      0.363636     0.555556        0.750      0.934426   
2    0.176471      0.75      0.181818     0.444444        0.375      0.983607   
3    0.235294      0.75      0.772727     0.666667        0.500      0.524590   
4    0.823529      0.25      0.090909     0.555556        0.500      0.655738   

   RoofStyle  Exterior1st  BsmtQual  BsmtExposure  BsmtFinSF1  TotalBsmtSF  \
0        1.0          0.2      0.50          0.25    0.539381     0.634747   
1        0.0          0.2      0.50          0.25    0.178319     0.251404   
2        0.0          0.3      0.50          0.25    0.081858     0.221148   
3        1.0          0.7      0.75          0.25    0.173451     0.361822   
4        0.0          0.5      0.50          0.25    0.000000     0.163755   

   HeatingQC  CentralAir  1stFlrSF  GrLivArea  KitchenQual  Fireplaces  \
0        0.5         1.0  0.889975   0.765003     0.333333    0.666667   
1        0.5         1.0  0.464500   0.588381     0.000000    0.666667   
2        0.5         1.0  0.474058   0.485565     0.666667    0.333333   
3        1.0         1.0  0.547319   0.682328     0.333333    0.333333   
4        0.5         1.0  0.199366   0.448882     0.333333    0.000000   

   FireplaceQu  GarageType  GarageFinish  GarageCars  GarageCond  PavedDrive  \
0          0.6         0.8      0.666667        0.50         1.0         1.0   
1          0.6         0.8      0.333333        0.25         1.0         1.0   
2          0.6         0.4      0.333333        0.25         1.0         1.0   
3          0.6         0.8      1.000000        0.50         1.0         1.0   
4          0.2         0.4      0.333333        0.25         1.0         1.0   

   SaleCondition  
0           0.25  
1           0.75  
2           0.75  
3           0.75  
4           0.50

In [14]:
y_test.head()

SalePrice
0  12.209188
1  11.798104
2  11.608236
3  12.165251
4  11.385092

In [15]:
# Multiple Regression
from sklearn.linear_model import LinearRegression
multipleregressor = LinearRegression()
multipleregressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred = multipleregressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred, y_test),1))

[[12.31 12.21]
 [11.96 11.8 ]
 [11.64 11.61]
 [12.32 12.17]
 [11.44 11.39]
 [11.46 11.35]
 [12.44 12.55]
 [11.68 11.86]
 [13.22 13.52]
 [11.97 11.91]
 [12.26 12.25]
 [12.   11.83]
 [12.32 12.32]
 [11.69 11.72]
 [11.76 11.69]
 [11.88 11.88]
 [12.35 12.15]
 [11.69 11.72]
 [11.81 11.91]
 [12.11 11.95]
 [11.77 12.02]
 [11.89 11.88]
 [11.39 11.61]
 [11.98 12.07]
 [12.16 12.13]
 [12.16 12.03]
 [12.09 12.09]
 [11.2  11.34]
 [12.52 12.68]
 [11.61 11.68]
 [11.9  11.61]
 [12.18 12.27]
 [11.93 11.96]
 [12.59 12.43]
 [12.65 12.83]
 [12.14 12.07]
 [12.55 12.53]
 [11.71 11.63]
 [12.36 12.48]
 [12.71 12.69]
 [12.25 12.4 ]
 [11.8  11.78]
 [12.23 12.01]
 [12.61 12.54]
 [12.72 12.91]
 [11.84 11.69]
 [11.57 11.74]
 [11.73 11.76]
 [11.98 12.06]
 [11.41 11.35]
 [12.89 12.93]
 [11.88 11.96]
 [12.05 12.03]
 [11.29 11.51]
 [12.35 12.52]
 [11.61 11.72]
 [11.61 11.79]
 [12.31 12.39]
 [11.82 11.84]
 [11.47 11.65]
 [11.9  11.83]
 [11.7  11.81]
 [11.87 11.81]
 [11.97 12.1 ]
 [12.24 12.17]
 [11.96 11.96]
 [11.75 11

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8184466206729886

In [20]:
# Decision tree regression
from sklearn.tree import DecisionTreeRegressor
decision_tree_regressor = DecisionTreeRegressor(random_state = 0)
decision_tree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [29]:
y_pred = decision_tree_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test),1))

[[12.43 12.21]
 [11.82 11.8 ]
 [11.   11.61]
 [12.24 12.17]
 [11.37 11.39]
 [11.42 11.35]
 [12.38 12.55]
 [11.74 11.86]
 [13.53 13.52]
 [11.93 11.91]
 [12.43 12.25]
 [12.01 11.83]
 [12.31 12.32]
 [11.04 11.72]
 [11.85 11.69]
 [11.79 11.88]
 [12.25 12.15]
 [11.29 11.72]
 [11.76 11.91]
 [12.49 11.95]
 [11.88 12.02]
 [11.88 11.88]
 [11.34 11.61]
 [12.09 12.07]
 [12.19 12.13]
 [12.28 12.03]
 [12.06 12.09]
 [11.23 11.34]
 [12.7  12.68]
 [11.74 11.68]
 [11.87 11.61]
 [12.12 12.27]
 [11.78 11.96]
 [12.54 12.43]
 [12.89 12.83]
 [12.03 12.07]
 [12.7  12.53]
 [11.86 11.63]
 [12.43 12.48]
 [12.66 12.69]
 [12.32 12.4 ]
 [11.72 11.78]
 [11.98 12.01]
 [12.46 12.54]
 [12.62 12.91]
 [11.87 11.69]
 [11.6  11.74]
 [11.74 11.76]
 [12.09 12.06]
 [11.36 11.35]
 [12.77 12.93]
 [11.91 11.96]
 [12.11 12.03]
 [11.62 11.51]
 [12.54 12.52]
 [11.57 11.72]
 [11.1  11.79]
 [12.28 12.39]
 [11.91 11.84]
 [11.68 11.65]
 [12.07 11.83]
 [11.82 11.81]
 [11.92 11.81]
 [12.   12.1 ]
 [11.88 12.17]
 [11.92 11.96]
 [11.9  11

In [30]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.684801310740415

In [44]:
# Random Forest
from sklearn.ensemble import RandomForestRegressor
random_forest_regressor = RandomForestRegressor(n_estimators = 15, random_state = 0)
random_forest_regressor.fit(X_train, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=15, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [45]:
y_pred = random_forest_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test),1))

[[12.39 12.21]
 [11.81 11.8 ]
 [11.5  11.61]
 [12.34 12.17]
 [11.42 11.39]
 [11.57 11.35]
 [12.38 12.55]
 [11.68 11.86]
 [13.25 13.52]
 [11.94 11.91]
 [12.32 12.25]
 [12.02 11.83]
 [12.34 12.32]
 [11.56 11.72]
 [11.74 11.69]
 [11.84 11.88]
 [12.29 12.15]
 [11.7  11.72]
 [11.87 11.91]
 [12.22 11.95]
 [11.83 12.02]
 [11.84 11.88]
 [11.48 11.61]
 [12.09 12.07]
 [12.13 12.13]
 [12.28 12.03]
 [12.06 12.09]
 [11.22 11.34]
 [12.64 12.68]
 [11.72 11.68]
 [11.72 11.61]
 [12.21 12.27]
 [11.84 11.96]
 [12.52 12.43]
 [12.66 12.83]
 [12.12 12.07]
 [12.64 12.53]
 [11.7  11.63]
 [12.4  12.48]
 [12.64 12.69]
 [12.26 12.4 ]
 [11.73 11.78]
 [12.14 12.01]
 [12.63 12.54]
 [12.63 12.91]
 [11.85 11.69]
 [11.66 11.74]
 [11.75 11.76]
 [11.9  12.06]
 [11.46 11.35]
 [12.82 12.93]
 [11.89 11.96]
 [12.05 12.03]
 [11.48 11.51]
 [12.42 12.52]
 [11.61 11.72]
 [11.78 11.79]
 [12.34 12.39]
 [11.88 11.84]
 [11.53 11.65]
 [11.89 11.83]
 [11.79 11.81]
 [11.94 11.81]
 [11.95 12.1 ]
 [12.23 12.17]
 [11.84 11.96]
 [11.8  11

In [46]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8841192364988845